### ISSUE TITLE
안녕하세요. 메모리와 CPU 점유율 문제 때문에 질문드립니다.

### ISSUE THREAD

**Issue by soon91jae** [minhoryang/minhoryang.github.io#21]
오랜만입니다. 그동안 잘지내셨는지요? 다름이 아니라 이번에 대규모 데이터로 word embedding을 진행하는 와중에 메모리 사용량이 커지니 cpu 점유율이 매우 줄어드는 문제가 발생했습니다;;; 혹시 이런 문제가 발생하는 이유랑 해결법을 알 수 있을까요? priority를 매우 낮게 설정했는데도 스케쥴러에서 cpu에게 넘겨주질 않는거 같아서요. 감사합니다.

![image](https://cloud.githubusercontent.com/assets/9526659/18342247/ceb2509c-75e8-11e6-9bca-38fd86edd887.png)

**Comment by minhoryang** [comment]
엌 하이하이요 푸시가안와서 이제 확인햇다.
1. 메모리 사용량이 커져서 스왑으로 간거 아니지 확인해봐.
스크린샷이 htop이니까 swap을 볼 수 있어요.
실제 너가 쓸 수 있는 양의 메모리임?
IO Bound가 OS레벨에서 걸려버린거아닐까?
2. 님 nice를 낮춘거아님? priority가 아니라?
3. 프로세스가 현재 D State래 http://stackoverflow.com/questions/223644/what-is-an-uninterruptable-process
https://www.novell.com/support/kb/doc.php?id=7002725 여기보니까 swap이 이유일 것 같아.
