### ISSUE TITLE
혹시 cmusphinx 언어 인식에서 한국어 language model쪽 알고 계신지?

### ISSUE THREAD

**Issue by thorpe** [minhoryang/minhoryang.github.io#22]
안녕하세요. 이광복입니다.
질문은 모두 하라고해서.. 
cmusphinx 한국어 인지부분의 모델링을 만들려고 몇달부처 조금 조금씩 하고있는데.
조금 조금씩 진척은 있는데 잘 안되네요.

혹시 cmusphinx 언어 인식에서 한국어 language model쪽 알고 계신지?

정보공유좀...

**Comment by minhoryang** [comment]
좋은질문입니다! ㅠㅠ 하지만 제가 대학원에서 나온지 좀 되어서 관련 기억이 많이 남아있지않네요 ㅠㅠ
[서강대학교 음성언어연구실](speech.sogang.ac.kr)에 물어보시면 매우 좋을 것 같습니다.
