### ISSUE TITLE
익숙하지 않은 언어 혹은 프레임워크에 대한 사용법이나 지식을 습득하려고 하실 때 어떤 방법으로 학습하시나요?

### ISSUE THREAD

**Issue by Leop0ld** [minhoryang/minhoryang.github.io#24]
여러 상황(회사에서 당장 프로덕트를 만들어야할 때 혹은 재밌어보여서 토이 프로젝트를 간단하게 하고 싶을 때...? 두 개의 갭이 조금 크지만 ㅠㅠ)에서 보통 어떻게 학습하시는 지 궁금합니다.

익숙하지 않은 패러다임의 언어나 익숙하지 않은 디자인 패턴을 사용하는 프레임워크는 어떻게 학습하시는 지 혹은 따로 방법이 있으신 지 궁금해서 이슈 남깁니다.

**Comment by minhoryang** [comment]
익숙하지 않을 땐 쓰지 않는 편을 선호하는데요.
Battery-included던지 풀려고하는 문제와 결이 같던지 하면 배워서라도 써야죠.

**Comment by minhoryang** [comment]
무언가를 새로 배워야할 때 제가 가장 먼저 궁금해 하는 부분이 말씀하신 패러다임과 디자인 패턴입니다.
패러다임은 소개글을 통해서 파악할 수 있습니다.
그래서 신뢰할 수 있고 통찰력이 보이는 기술문서나 블로그, 아티클, 커밋로그/PR, 메일링리스트를 찾아서 이 패러다임의 배경과 이유를 알아냅니다.
다른 경우와의 비교를 찾아내면 좋고, 샘플 프로젝트나 벤치마크 결과와 분석(+ 재현가능한 스크립트)를 찾아내면 최고고, 역사와 배경, 이유를 찾아내면 만족하는 편입니다.

(위의 문서에서도 찾을 수 있겠지만) 디자인 패턴의 경우는 그 패키지의 생태계를 뒤져서 공부합니다.
패턴은 남들과 함께 쓸 경우 효과가 더 강해지는 경향이 있으므로, 사용량이 많거나 의존도가 강한 패키지를 찾아서 코드를 크로스체크합니다.
어떻게 사용하는지, 가이드/문서는 어떤지, 이슈(버그)의 경향은 어떤지, 커밋과 PR은 어떻게 쪼개지는지, 등등으로 파악합니다.

**Comment by minhoryang** [comment]
토이 프로젝트를 할 때는 그냥 디자인 패턴만 맞추면 되니 빠르게 끝나는 편인데, 회사에서 쓰겠다고 할 때는 위에 있는 것을 다 하고도 부족합니다.
커뮤니티가 활발한지, 테스트는 충분한지,
쌓여있는 이슈나 논의들도 읽어보려는 편이고
컨텍포인트도 미리 만들어놀려고하고
컨텍포인트를 만들기 위해 토이프로젝트를 합니다.
이슈도 남기고 PR도 던지면서요.
가장 중요한 건 *교육할 수 있는지*입니다.

**Comment by minhoryang** [comment]
이걸 제가 다 할 순 없으니, 당연히 해봣을 것 같은 친구들에게 물어보는 편이구요.

**Comment by minhoryang** [comment]
토이프로젝트를 시작하기 전에 디자인문서를 먼저 짜고 시작하는데, 기술적 목표를 조금 빡세게 잡는 편이에요.
Angular2나 Ionic2에서 묘듈공유가 가능한지, 리포분리가 가능한지, 모노리포가 되는지, 빌드가 묶어서 되는지, 테스트코드가 공유가능한지, 로직에서 플랫폼을 파악할 수 있는지, 뭐 이런식이고
가설검증을 우선 다 하고, 짜려고하면 열정이 식어버려서
다음 토이로 넘어갑니다=__=:;;;

**Comment by minhoryang** [comment]
그래도 이해가 안되는 건 계속 이해가 안되는데,
OAuth2랑 OpenID쪽이 일년째 스펙을 읽고 있는데 머릿속에서 정립이 안되고 있구요. (구현은 다 되는데 왠지 이렇게하면 안될것만같은느낌)
Vagrant랑 CSS는 공부하기가 적극적으로 싫고,
Django는 왠지 싫었는데 이번 토이 컨트리뷰션으로 해보니까 좋았구요.
Hashicorp Vault를 오늘 드디어 한붓그리기가 끝나서 기분이 매우 좋습니다:) 1년걸렸네요ㅎㅎㅎㅎ

**Comment by minhoryang** [comment]
감사합니다!!!!! 앞으로도 재밌는거 하면서 자주 마주쳐요!
