### ISSUE TITLE
릴리즈 및 이슈 히스토리 추적

### ISSUE THREAD

**Issue by devmasme** [minhoryang/minhoryang.github.io#26]
@minhoryang 님 예전에 휴먼스케이프에서 구현해주셨던 우리가 사용하는 라이브러리, 프레임워크 모니터링하며 새 버전이 릴리즈 되거나 이유가 등록되었을 때 슬랙(developers-update 채널)으로 아래와 같이 알림오는 것 어떻게 구현하셨었는지 기억하시나요? ㅎㅎ IFTTT 이용했던 거 같은데..

<img width="563" alt="스크린샷 2019-12-05 오후 12 26 38" src="https://user-images.githubusercontent.com/6169074/70201626-8723fe80-175a-11ea-82e1-92897fce94e7.png">

**Comment by minhoryang** [comment]
IFTTT로 RSS구독 걸어놓은 거에요!
Github RSS주소를 검색하시면 얻을 수 있을거에요. 주소 규칙이 뻔해서 리포이름만 바꿔치기하면 다 됩니다!

**Comment by minhoryang** [comment]
그런데 지금은 이 RSS 기능이 깃허브에서 제공 안되고 있을 수도 있겠네요

**Comment by devmasme** [comment]
답변 감사합니다. 역시 모든 질문은 스택오버플로우가 아닌 스택오브라이언에게!
