### ISSUE TITLE
Dear by far the most outstanding, real "Software Engineer"

### ISSUE THREAD

**Issue by SeiwonPark** [minhoryang/minhoryang.github.io#29]
민호님 안녕하세요!ㅎㅎ 오랜만에 인사드립니다.

민호님께 좋은 영향을 많이 받고 즐겁게 개발하며 살고 있습니다. 민호님은 제가 생각하는 최고이자 진정한 개발자이십니다ㅎㅎ 
인사드리고 싶은데 슬랙은 너무 바쁘실 것 같아서.. 이렇게 인사드립니다.

질문하는 곳이니 질문도 하나 있습니다! 
어떠한 종류든 책 한권만 추천해주실 수 있을까요?  개발 서적이든 시집이든 성경이든 민호님께서 추천해주시는 책 정독하고 싶습니다.

**Comment by minhoryang** [comment]
@SeiwonPark 으악. 안녕안녕! https://aosabook.org/en/ 이 시리즈 책이 좋은데, 한글로 나와있는게 있어. 구매할 필요는 없구, https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000003160821 한번 목차 읽어보구 앞부분 미리본다음에 마음에 든다면 [도서관](https://www.nl.go.kr/kolisnet/search/searchResultEditonList.do?tab=ALL&subTab=&pageNum=1&pageSize=15&sortField=&sortOrder=&facetCollType=&facetYear=&facetKdc=&facetLang=&keywordType1=total&keyword1=%EC%98%A4%ED%94%88+%EC%86%8C%EC%8A%A4+%EC%86%8C%ED%94%84%ED%8A%B8%EC%9B%A8%EC%96%B4+%EC%95%84%ED%82%A4%ED%85%8D%EC%B2%98&bookFilter=BKGM%2CNK&ufKey=28555541)에서 빌려봐요. 물론 영어로 본다면 바로 웹에서도 볼 수 있어요 :)

**Comment by SeiwonPark** [comment]
😙 감사합니다!!! ㅎㅎㅎ 와우 "All the material is free to read and re-use under open licenses"! 그리고 history of how software is structured를 말하는 책이라, 민호님께서 해주신 조언과도 잘 매치되는 책들이네요ㅎㅎ. 마침 오늘 책을 다 읽은 참이라 바로 읽어보겠습니다.

바쁘신 와중에 너무너무 감사합니다🤗 여유 되실 때 여쭙고 찾아뵙겠습니다ㅎㅎ 날씨가 쌀쌀해졌는데 항상 건강하세요!!
