### ISSUE TITLE
Java Console Program에서 화면을 지우고싶어요.

### ISSUE THREAD

**Issue by soon91jae** [minhoryang/minhoryang.github.io#4]
How can i clear console in windows with java?
I have repeated every code in stackoverflow but In windows 7 but it didn't work.

**Comment by minhoryang** [comment]
안해본건데 구글링해보니 
https://github.com/jline/jline2/wiki/Terminal-Factory-Configuration
이게 뭔가 해결을 해줄 수 있을 것 같은데욥?
윈도우 환경이라는게 많이 걸리네용...
한번 짜봐야겠네//

**Comment by minhoryang** [comment]
저녁먹고와서 짜볼게용.

**Comment by minhoryang** [comment]
윈도우가 되는 곳에서 하느라 시간이 좀 걸렸네용;
jline2로 되네요! 한번 확인해보세요!
https://gist.github.com/minhoryang/588700d6d6ce3fb44183

**Comment by soon91jae** [comment]
감사합니다. 덕분에 잘 해결돼었습니다.
