### ISSUE TITLE
pintOS 출력 질문입니다.

### ISSUE THREAD

**Issue by juice500ml** [minhoryang/minhoryang.github.io#5]
![2015-10-14 7 52 00](https://cloud.githubusercontent.com/assets/7028312/10481667/2f35e23e-72ad-11e5-9d0c-2f1493980b35.png)
char* filename이 뭔지 궁금해서 출력해보기 위해 출력문을 start_process()에 넣었습니다.
![2015-10-14 7 51 39](https://cloud.githubusercontent.com/assets/7028312/10481683/4d3cd986-72ad-11e5-94aa-831559c232dd.png)

![url](https://cloud.githubusercontent.com/assets/7028312/10481701/730d4394-72ad-11e5-96e6-0985dee0f59a.jpg)

**Comment by juice500ml** [comment]
process_execute()에 넣으니 나오네요.
해결되었습니다! 감사합니다 하하

**Comment by minhoryang** [comment]
# 그냥 해도 되야하는데?ㅋㅋㅋㅋㅋㅋㅋ
왜냐면
## 0. Pintos Guidebook에서 ["Debugging Tools" Appendix](https://web.stanford.edu/class/cs140/projects/pintos/pintos_10.html)를 보면,
"Don't underestimate the value of printf(). The way printf() is implemented in Pintos, you can call it from practically anywhere in the kernel, whether it's in a kernel thread or an interrupt handler, almost regardless of what locks are held."
라고 되어있어요.
### 그러니까 여기에 따라서, "practically" printf는 동작해야합니다.

## < 순서대로보자면 >
### 1. parent kernel이
### 2. [userprog/process.c: process_execute()](https://github.com/minhoryang/MinHo-JaeHyun-OperatingSystem-Pintos-Prj/blob/cb32ae2e609633a93a4e7e6594321db9a41caf63/pintos/src/userprog/process.c#L29)에서
### 3. [threads/thread.c: thread_create()](https://github.com/minhoryang/MinHo-JaeHyun-OperatingSystem-Pintos-Prj/blob/cb32ae2e609633a93a4e7e6594321db9a41caf63/pintos/src/userprog/process.c#L42)를 통해
### 4. [userprog/process.c: start_process()](https://github.com/minhoryang/MinHo-JaeHyun-OperatingSystem-Pintos-Prj/blob/cb32ae2e609633a93a4e7e6594321db9a41caf63/pintos/src/userprog/process.c#L51)를 돌리는 child thread를 생성하죠.
```c
  tid = thread_create (file_name, PRI_DEFAULT, start_process, fn_copy);
```
### 5. 그런데 start_process()는 아마 실행된 적이 없을겁니다 :)

## 이유는 < Callstack을 봅시다 >

### 6. Step2의 process_execute()는 [threads/init.c: run_task()](https://github.com/minhoryang/MinHo-JaeHyun-OperatingSystem-Pintos-Prj/blob/cb32ae2e609633a93a4e7e6594321db9a41caf63/pintos/src/threads/init.c#L282)가 실행하구요.
```c
  process_wait (process_execute (task));
```
### 7. process_execute()가 끝나면 [userprog/process.c: process_wait()](https://github.com/minhoryang/MinHo-JaeHyun-OperatingSystem-Pintos-Prj/blob/cb32ae2e609633a93a4e7e6594321db9a41caf63/pintos/src/userprog/process.c#L89)을 호출합니다.
```c
int
process_wait (tid_t child_tid UNUSED) 
{
  return -1;
}
```
### 8. 이론상 process_wait()은 Child Thread들 중 한 놈이 죽기까지 return을 안해주고 있어야합니다. 그러면서 schedule()이 어딘가(?)에서 수행되어야 하죠. (후후) 그래야 child에게로 차례가 넘어갑니다 (후후후) 그러니까 process_wait()을 구현하세요!

**Comment by minhoryang** [comment]
관전포인트 1. schedule()부분에 진짜 printf()가 수행되지 않는 부분이 있습니다!
관전포인트 2. schedule()는 누가 어디서 불러서 어떻게 돌고있을까요?
