### ISSUE TITLE
안녕하세요, pickle관련하여 하나만 여쭤보고싶은게 있어서용

### ISSUE THREAD

**Issue by soon91jae** [minhoryang/minhoryang.github.io#7]
pickle로 클래스 저장을 하는데 용량이 크니까 바로 픽 하고 죽어버리네용.
 찾아보니까 pickle protocol 3 까지는 32bit로 opcode를 만들어서 그래서 protocol을 4로 쓰라고 하네요 ㅠㅜ
근데 제가 짠 프로그램이 파이썬 2.7 기반이라 protocol 4를 쓸 수가 없어요.......
pickle로 큰 데이터를 저장하는 경우에는 어떻게 하는게 좋을까요?

**Comment by minhoryang** [comment]
음. 우선 저는 pickle을 안쓰는 편이구요. 다른 serializer library를 찾아보는게 어때요?
json도 추천하는데...
MessagePack이라는 것도 있습니다.

**Comment by minhoryang** [comment]
사실 전 protobuf를 사랑합니다.

**Comment by minhoryang** [comment]
PyTables이라는것도있다네요.

**Comment by soon91jae** [comment]
오홍 감사합니다. 쓰는 NN tool에서 pickle을 지원해서 그거로 하려다보니 그랬어요 감사합니다!!!
